### ISSUE TITLE
Possible to use to create UI?

### ISSUE THREAD

**Issue by fan-tom** [viniarck/nvimhost-scala#14]
Is it possible to use this plugin to create custom UI? If no, are there any plans to make it possible?

**Comment by viniarck** [comment]
Hi @fan-tom, I'm sorry for this late reply. Missed this on my notification. A custom UI for neovim works as a plugin, however other events like `redraw` and UI related should be handled, it should be possible to receive these events on https://github.com/viniarck/nvimhost-scala/blob/master/src/main/scala/io/github/viniarck/nvimhost/Plugin.scala#L72. Feel free to explore try creating one, you can start by following this guide https://github.com/viniarck/nvimhost-scala/blob/master/docs/plugin_how_to.md, also feel free to contribute back. 

Have nice day.

**Comment by smolck** [comment]
@fan-tom Did you ever try this?

Also, @viniarck, is it possible to just spawn a Neovim process and communicate with it, e.g. `val nvim = new Nvim(); println(nvim.eval('1 + 1'))`? I think that would make this sort of thing pretty straightforward.
