### ISSUE TITLE
How to use with jobstart

### ISSUE THREAD

**Issue by smolck** [viniarck/nvimhost-scala#9]
Hello! I’m interested in writing a plugin using this library, but there doesn’t appear to be any documentation on how to create an application which Neovim can communicate with via stdin/stdout after starting the app [binary] with `jobstart()`. Would you mind giving a short example of this, with the necessary Scala and Vimscript code?

For example, the following article details how to do this with Rust and the neovim-lib library: https://blog.usejournal.com/a-detailed-guide-to-writing-your-first-neovim-plugin-in-rust-a81604c606b1

Something like that (but shorter and just the code) would be very helpful.

**Comment by viniarck** [comment]
Hi @smolck. Sure. I'm glad you're planning to develop a Scala plugin. I've just merged a PR with more docs, see https://github.com/viniarck/nvimhost-scala/blob/master/docs/plugin_how_to.md.  

Feel free to contribute back. If you enconter any issues let me know. I've also just published a new version of this library `1.1.0` for Scala 2.13.

**Comment by smolck** [comment]
Okay, thanks for the quick reply! I’ll see how it goes and post here as/if necessary. I may also post a link to the project on GitHub (assuming I get that far) here for future reference/an example plugin, if you don’t mind ;)

**Comment by viniarck** [comment]
Sounds great! Send the link once you get it done and feel free to send a PR with the link of the project. It would be nice to have a section in the README.md with plugins hosted by nvimhost-scala.

**Comment by smolck** [comment]
@viniarck Why is `NVIM_LISTEN_ADDRESS` (and specifying said address in Scala) necessary to create a plugin? Could that not be omitted in most cases?

**Comment by viniarck** [comment]
@smolck, neovim exposes its RPC API either via IPC (over Unix Socket domain), which is the default, or via a TCP socket. For example, if you start neovim, by typing `nvim`, and then type `:echo $NVIM_LISTEN_ADDRESS` you're going to see that neovim has automatically picked an IPC socket on `/tmp/<nvimValue>`. So, it's up to the library to decide whether it's going to use IPC or TCP. When I initially implemented this library I had some dependencies issues with IPC, so I went ahead and implemented with TCP. FYI, other nvim host libraries also do that, Clojure for example does too https://github.com/clojure-vim/neovim-client.

To tell nvim to expose the address via TCP you can either export the `NVIM_LISTEN_ADDRESS` in advance, or with the `--listen` option, `nvim --listen 127.0.0.1:7777`

**Comment by smolck** [comment]
Thank you for the explanation! So does that mean in order for the user to use a plugin made with this library, s/he will have to specify that TCP address? I guess I could (optionally) export `NVIM_LISTEN_ADDRESS` with the .vim file before loading the scala plugin itself, that way the user doesn't have to type `nvim --listen <addr>:<port>` or export `NVIM_LISTEN_ADDRESS` in order to use the plugin.

**Comment by viniarck** [comment]
Yes, currently it does. In the future I plan to add support for IPC though, to facilitate for end users.

**Comment by smolck** [comment]
@viniarck What needs to be done to add IPC support?
